version: '3.3'

services:
  nginx:
      image: nginx:1.13-alpine
      restart: unless-stopped
      ports:
        - "443:443"
      volumes:
        - ../nginx/conf.prod:/etc/nginx/conf.d
        - ../../back_static:/opt/services/backend/back_static
        - ../../back_media:/opt/services/backend/back_media
        - /etc/letsencrypt:/etc/letsencrypt
      networks:
        - nginx_network
