# Generated by Django 5.1.6 on 2025-02-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_message_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='image',
        ),
        migrations.CreateModel(
            name='TelegramMessageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='telegram_images/', verbose_name='Изображение')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='telegram_message_parser.telegrammessage', verbose_name='Сообщение')),
            ],
        ),
    ]
