# Generated by Django 5.1.6 on 2025-02-14 14:01

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя контакта')),
                ('contact_value', models.CharField(max_length=255, unique=True, verbose_name='Номер или юзернейм контакта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreparedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сообщения')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('voice', 'Голосовое сообщение'), ('round', 'Видеокружок')], max_length=10, verbose_name='Тип сообщения')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='Медиафайл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255, unique=True, verbose_name='Название сессии')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('api_id', models.IntegerField(help_text='Получить можно здесь: https://my.telegram.org/apps', verbose_name='API ID')),
                ('api_hash', models.CharField(max_length=255, verbose_name='API Hash')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('send_interval', models.IntegerField(default=5, verbose_name='Интервал отправки(в минутах)')),
                ('max_contacts_per_account', models.IntegerField(default=10, verbose_name='Максимальное количество контактов в аккаунте')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Запущена'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус рассылки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(to='telegram_sender.contact', verbose_name='Контакты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_sender.preparedmessage', verbose_name='Шаблон сообщения')),
                ('accounts', models.ManyToManyField(to='telegram_sender.telegramaccount', verbose_name='Аккаунты')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Отправлен'), ('failed', 'Ошибка')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_sender.campaign', verbose_name='Рассылка')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_sender.telegramaccount', verbose_name='Аккаунт')),
            ],
        ),
    ]
