# Generated by Django 5.1.6 on 2025-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='messagelog',
            options={'verbose_name': 'Лог сообщений', 'verbose_name_plural': 'Логи сообщений'},
        ),
        migrations.AlterModelOptions(
            name='preparedmessage',
            options={'verbose_name': 'Заготовленное сообщение', 'verbose_name_plural': 'Заготовленные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'verbose_name': 'Telegram аккаунт', 'verbose_name_plural': 'Telegram аккаунты'},
        ),
        migrations.RemoveField(
            model_name='telegramaccount',
            name='api_hash',
        ),
        migrations.RemoveField(
            model_name='telegramaccount',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, verbose_name='Активен'),
        ),
    ]
